on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy .env file
        run: cp .env.test .env

      - name: Export environment variables
        run: export $(grep -v '^#' .env | xargs)

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true -X

      - name: Start Docker
        run: docker-compose up -d db

      - name: Run tests
        run: mvn test -X -DMANDACARU_POSTGRES_PORT=$MANDACARU_POSTGRES_PORT -DMANDACARU_POSTGRES_DB=$MANDACARU_POSTGRES_DB -DMANDACARU_POSTGRES_USER=$MANDACARU_POSTGRES_USER -DMANDACARU_POSTGRES_PASSWORD=$MANDACARU_POSTGRES_PASSWORD

      - name: Stop Docker
        run: docker-compose down
