on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install -X

      - name: Start Docker
        run: docker-compose up -d

      - name: Run tests
        run: mvn test

      - name: Stop Docker
        run: docker-compose down
      